### ISSUE TITLE
Some ideas for enhancements. 

### ISSUE THREAD

**Issue by rsxgti** [ohld/instabot#20]
Some ideas for good enhancement 
- [x] following someone elses followers  
- [x] Unfollow following after certain amount of days
- [x] Like media from list of users
- [x] Whitelist/blacklist users

**Comment by ohld** [comment]
About `Unfollow following after certain amount of days`:
You can _make a checkpoint_ and then _revert to checkpoint_ after certain amount of days. 
Now you can do that, but I don't know yet how to make it clear and more easier to use.
Try to do this with checkpoints and give feedback about it's complication.

**Comment by ohld** [comment]
Finish with black/whitelists. 
Check out the example to understand how to use them.
https://github.com/ohld/instabot/tree/master/examples/black-whitelist

**Comment by ohld** [comment]
"Like media from list of users."
You can iterate over list of users and run `bot.like_user_id(user_id)`

**Comment by DrCherry** [comment]
I'd like to add a threshold for likes.  For example if a media has more than 100 likes, I'd like to skip it and move on.  What do you think is the best way to set this?  self.like_threshold = 30

**Comment by ohld** [comment]
I added bot_limits.py file. There we should add any logic to like or not to like, to follow or not to follow. Like threshold is a great idea. Moreover we should add limits based on user info. For example: if person's followings / followers less than 0.1 - selebram and he will not follow us.

**Comment by DrCherry** [comment]
how about MAX_LIKES_TO_LIKE.

**Comment by rsxgti** [comment]
Max_likes_to_like is already part of limits.py

**Comment by DrCherry** [comment]
Maybe following someone elses followers next?  I noticed that's an endpoint in the instagram api.

**Comment by rsxgti** [comment]
Im already using Instagram-API to follow someone elses followers :) it can be done

**Comment by rsxgti** [comment]
Maybe bulk uploading with delay like the one in instagram-api.py
